import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Poppins, Newsreader } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

// Define your fonts and assign them CSS variables
const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const geistSans = Geist({ subsets: ["latin"], variable: "--font-geist-sans" });
const geistMono = Geist_Mono({ subsets: ["latin"], variable: "--font-geist-mono" });
const newsreader = Newsreader({ subsets: ['latin'], variable: '--font-newsreader' });

// Poppins is static, so you must define the weights you plan to use
const poppins = Poppins({ 
  subsets: ['latin'], 
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-poppins' 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full antialiased",
        geistSans.variable,
        geistMono.variable,
        inter.variable,
        poppins.variable,
        newsreader.variable
      )}
    >
      <body className="min-h-full flex flex-col font-sans">{children}</body>
    </html>
  );
}